# Generated by Django 4.0.1 on 2022-01-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=32)),
                ('ip_addr', models.CharField(max_length=15)),
            ],
        ),
    ]
